name: Deployment Pipeline

on:
    push:
        branches:
            - master

jobs:
    simple_deployment_pipeline:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: '16'
            - name: Install dependencies
              run: npm install
            - name: Check style
              run: npm run eslint
            - name: Trigger deployment
              run: curl https://api.render.com/deploy/srv-ci5ft0tph6eh6mr8bnc0?key=DEv8qapxkAE?key=rnd_ejMELZ5QIwfnn27jBr6TBn3eNL57
